### ISSUE TITLE
Return type hint of Array2XML::convert should not be DOMDocument

### ISSUE THREAD

**Issue by SymenTimmermans** [JackieDo/Xml-Array#1]
The function returns a call to Array2XML::convertFrom, which returns $this (so actually the Array2XML) type. 
So instead of `@return DOMDocument`, it should `@return Array2XML`.

**Comment by JackieDo** [comment]
@SymenTimmermans :

A long time has passed, due to illness I do not have time to take care of my source code. For now, I'm back to upgrading and maintaining all the source code in the repository.

This issue has been fixed at commit fac2f6efd27dd16758e054142b5c2eaba8cc35fa

Many thanks for your discovery.
